FROM openjdk:11

ENV DEBIAN_FRONTEND noninteractive

USER root 
RUN apt-get update
RUN apt-get -qy dist-upgrade

RUN apt-get install -qy rsync curl openssh-server openssh-client vim nfs-common apt-transport-https locales krb5-user bash

RUN mkdir -p /data/hdfs-nfs/

RUN mkdir -p /var/logs/krb5/

WORKDIR /opt

# Install Hadoop
RUN curl -L https://archive.apache.org/dist/hadoop/core/hadoop-3.3.1/hadoop-3.3.1.tar.gz -s -o - | tar -xzf -
RUN mv hadoop-3.3.1 hadoop
RUN mkdir -p /opt/hadoop/logs
# Setup
WORKDIR /opt/hadoop
ENV HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
ENV HDFS_CONF_dfs_namenode_name_dir=file:///hadoop/dfs/name
RUN mkdir -p /hadoop/dfs/name
VOLUME /hadoop/dfs/name
USER root
SHELL ["/bin/bash", "-c"]
ENV PATH /opt/hadoop/bin:/opt/hadoop/sbin:$PATH
ENV JAVA_HOME /usr/local/openjdk-11
ENV REALM ${REALM:-EXAMPLE.COM}
ENV KADMIN_PRINCIPAL ${KADMIN_PRINCIPAL:-kadmin/admin}
ENV KADMIN_PASSWORD ${KADMIN_PASSWORD:-MITiys4K5}
ENV HADOOP_OPTS="-XX:+UseParallelGC -Xmx4g"

RUN echo "\n export HDFS_NAMENODE_USER=root \n" >> etc/hadoop/hadoop-env.sh &&\
    echo "\n export HDFS_DATANODE_USER=root \n" >> etc/hadoop/hadoop-env.sh &&\
	echo "\n export HDFS_SECONDARYNAMENODE_USER=root \n" >> etc/hadoop/hadoop-env.sh &&\
	echo "\n export JAVA_HOME=/usr/local/openjdk-11 \n" >> etc/hadoop/hadoop-env.sh &&\
	echo "\n export HADOOP_HOME=/opt/hadoop \n" >> etc/hadoop/hadoop-env.sh
	
# Configure ssh client
RUN ssh-keygen -t rsa -P '' -f ~/.ssh/id_rsa && \
    cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && \
    chmod 0600 ~/.ssh/authorized_keys

RUN echo "\nHost 0.0.0.0\n" >> ~/.ssh/config && \
    echo "   StrictHostKeyChecking no\n" >> ~/.ssh/config && \
    echo "   UserKnownHostsFile=/dev/null\n" >> ~/.ssh/config

# Disable sshd authentication
RUN echo "root:root" | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config
COPY core-site.xml etc/hadoop/core-site.xml
COPY hdfs-site.xml etc/hadoop/hdfs-site.xml
COPY yarn-site.xml etc/hadoop/yarn-site.xml
COPY kms-site.xml etc/hadoop/kms-site.xml
COPY mapred-site.xml etc/hadoop/mapred-site.xml
COPY krb5.conf /etc/krb5.conf
COPY configureKerberosClient.sh .
COPY wait-for-krb5-server.sh .

RUN chmod a+x wait-for-krb5-server.sh
RUN chmod a+x configureKerberosClient.sh

CMD ["./wait-for-krb5-server.sh"]



